export enum Country {
  UnitedStates = "United States",
  Canada = "Canada",
  UnitedKingdom = "United Kingdom",
  Germany = "Germany",
  France = "France",
  Italy = "Italy",
  Spain = "Spain",
  Japan = "Japan",
  China = "China",
  India = "India",
  Indonesia = "Indonesia",
  Brazil = "Brazil",
  Russia = "Russia",
  Mexico = "Mexico",
  Turkey = "Turkey",
  Ukraine = "Ukraine",
  Australia = "Australia",
  Switzerland = "Switzerland",
  Netherlands = "Netherlands",
  Belgium = "Belgium",
  Denmark = "Denmark",
  Finland = "Finland",
  Norway = "Norway",
  Sweden = "Sweden",
}
