name: linting, testing, and building
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  push: 
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  pipepline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies 
      run: npm install  
    - name: Build production project
      run: npm run build:prod
    - name: Linting 
      run: npm run lint
    - name: Stylelint
      run: npm run stylelint
    - name: Unit testing
      run: npm run test
    - name: Type checking
      run: npm run type-check
       
    

