name: linting, testing, and building
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  push: 
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  pipepline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies 
      run: npm ci 
    - name: Build production project
      run: npm run build:prod
    - name: Linting 
      run: npm run lint
      if: always()
    - name: Stylelint
      run: npm run stylelint
      if: always()
    - name: Unit testing
      run: npm run test
      if: always()
    - name: Type checking
      run: npm run type-check
      if: always()
    - name: Build storybook
      run: npm run build-storybook
      if: always()
    - name: Ui update
      run: npx loki update --reactUri="file:./storybook-static" --skipStories="Loader"
      if: always()
    - name: Screeenshot testing
      run: npm run test:screenshot
      if: always()
